ci: enhance deployment workflow by tagging Docker images

diff --git a/.github/workflows/build-publish-docker.yml b/.github/workflows/build-publish-docker.yml
--- a/.github/workflows/build-publish-docker.yml
+++ b/.github/workflows/build-publish-docker.yml
@@ -4,30 +4,21 @@ on:
     paths-ignore:
       - 'operations/deployments/openstad-headless/environments/acc/images.yml'
       - 'operations/deployments/openstad-headless/environments/prod/images.yml'
+      - 'charts/openstad-headless/values.yaml'
     branches:
-      - '**'
-    tags:
-      - "v*"
+      - 'develop'
+      - 'main'
+  pull_request:
+    branches:
+      - 'develop'
+      - 'main'
+  workflow_dispatch:
+    inputs:
+      branch:
+        description: 'Branch to run this workflow on'
+        required: true
+        default: 'develop'
 jobs:
-  unit-test:
-    name: Run unit tests
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      pull-requests: read
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - uses: actions/setup-node@v4
-        with:
-          node-version: 24
-
-      - name: Install dependencies
-        run: npm i
-
-      - name: Run Vitest tests
-        run: npm run test:unit
 
   generate-ci-build-id:
     name: Generate CI build ID
@@ -39,6 +30,9 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
+          persist-credentials: false
 
       - name: Set build ID
         id: set_build_id
@@ -57,20 +51,79 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
+          persist-credentials: false
 
       - name: Get chart version
         id: chart_version
         run: echo "openstad_version=$(yq '.version' ./charts/openstad-headless/Chart.yaml)" >> $GITHUB_OUTPUT
 
+  version-check:
+    name: Helm chart version check
+    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'main') || (github.ref == 'refs/heads/main')
+    needs: [get-openstad-version]
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: read
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
+          persist-credentials: false
+
+        # Get all releases from openstad-headless repository
+      - name: Get releases and check if current version exists
+        id: get-releases
+        run: |
+          RELEASES=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases" | jq -r '.[].tag_name')
+          if echo "$RELEASES" | grep -q "^v${{ needs.get-openstad-version.outputs.openstad_version }}$"; then
+              echo "Error: version ${{ needs.get-openstad-version.outputs.openstad_version }} already exists in ${{ github.repository }} releases."
+              exit 1
+          fi
+          echo "Version ${{ needs.get-openstad-version.outputs.openstad_version }} does not exist in ${{ github.repository }} releases."
+
+  unit-test:
+    name: Run unit tests
+    needs: [version-check]
+    if: always() && (needs.version-check.result == 'success' || needs.version-check.result == 'skipped')
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: read
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
+          persist-credentials: false
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version: 24
+
+      - name: Install dependencies
+        run: npm i
+
+      - name: Run Vitest tests
+        run: npm run test:unit
+
+
   component-test:
     name: Run Component tests
     runs-on: ubuntu-latest
-    needs: generate-ci-build-id
+    needs: [generate-ci-build-id, version-check]
+    if: always() && (needs.version-check.result == 'success' || needs.version-check.result == 'skipped')
     permissions:
       contents: read
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
+          persist-credentials: false
 
       - uses: actions/setup-node@v4
         with:
@@ -95,12 +148,16 @@ jobs:
   build-builder-stage:
     name: Build `builder` stage
     runs-on: ubuntu-latest
-    needs: [unit-test, component-test, get-openstad-version]
+    needs: [unit-test, component-test, get-openstad-version, version-check]
+    if: always() && (needs.version-check.result == 'success' || needs.version-check.result == 'skipped')
     permissions:
       contents: read
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
+          persist-credentials: false
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -125,7 +182,8 @@ jobs:
             .
   # define job to build and publish docker image
   build-and-push-docker-image:
-    needs: [get-openstad-version, build-builder-stage]
+    needs: [get-openstad-version, build-builder-stage, version-check]
+    if: always() && (needs.version-check.result == 'success' || needs.version-check.result == 'skipped')
     permissions:
       contents: read
       packages: write
@@ -146,6 +204,9 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
+          persist-credentials: false
 
       - name: Restore base build cache
         uses: actions/cache@v3
@@ -159,19 +220,32 @@ jobs:
         name: Set correct build target
         run: echo "BUILD_TARGET=${{ matrix.build-target}}" >> $GITHUB_ENV
 
+      - name: Determine image tags
+        id: set_tags
+        run: |
+          if [[ "${GITHUB_REF}" == "refs/heads/main" || ( "${GITHUB_EVENT_NAME}" == "workflow_dispatch" && "${{ github.event.inputs.branch }}" == "main" ) ]]; then
+            echo "tags<<EOF" >> $GITHUB_OUTPUT
+            echo "type=raw,value=v${{ needs.get-openstad-version.outputs.openstad_version }}",priority=900 >> $GITHUB_OUTPUT
+            echo "type=ref,event=branch,suffix=-{{sha}}",priority=700 >> $GITHUB_OUTPUT
+            echo "type=ref,event=tag" >> $GITHUB_OUTPUT
+            echo "type=ref,event=pr" >> $GITHUB_OUTPUT
+            echo "type=raw,value=latest,enable={{is_default_branch}}" >> $GITHUB_OUTPUT
+            echo "EOF" >> $GITHUB_OUTPUT
+          else
+            echo "tags<<EOF" >> $GITHUB_OUTPUT
+            echo "type=ref,event=branch,suffix=-{{sha}}",priority=700 >> $GITHUB_OUTPUT
+            echo "type=ref,event=tag" >> $GITHUB_OUTPUT
+            echo "type=ref,event=pr" >> $GITHUB_OUTPUT
+            echo "type=raw,value=latest,enable={{is_default_branch}}" >> $GITHUB_OUTPUT
+            echo "EOF" >> $GITHUB_OUTPUT
+          fi
+
       - name: Docker meta
         id: meta
         uses: docker/metadata-action@v5
         with:
           images: ${{ env.IMAGE }}
-          tags: |
-            # branch event
-            type=ref,event=branch,suffix=-{{sha}}
-            # tag event
-            type=ref,event=tag
-            # latest tag
-            type=raw,value=latest,enable={{is_default_branch}}
-
+          tags: ${{ steps.set_tags.outputs.tags }}
 
       - name: Set up Docker Buildx
         id: buildx
@@ -195,6 +269,7 @@ jobs:
             APP=${{ matrix.app }}
             OPENSTAD_VERSION=${{ needs.get-openstad-version.outputs.openstad_version }}
           cache-from: type=local,src=/tmp/.buildx-cache
+
       - name: Add image output
         id: image_output
         run: echo "image_tag=${{ steps.meta.outputs.version }}" >> "$GITHUB_OUTPUT"
@@ -203,12 +278,15 @@ jobs:
     name: Run E2E tests
     runs-on: ubuntu-latest
     needs: [generate-ci-build-id, build-and-push-docker-image]
-    #if: github.event_name == 'pull_request' && github.base_ref == 'main'
+    if: github.event_name == 'pull_request'
     permissions:
       contents: read
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
+          persist-credentials: false
 
       - name: Load .testing.env into environment
         run: |
@@ -285,11 +363,13 @@ jobs:
 
   set-images-in-yaml-and-commit:
     name: Set images in yaml and commit
-    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') && (needs.e2e-test.result == 'success' || needs.e2e-test.result == 'skipped')
+    if: always() && ((github.event_name == 'workflow_dispatch' && (github.event.inputs.branch == 'main' || github.event.inputs.branch == 'develop')) || (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')) && (needs.e2e-test.result == 'success' || needs.e2e-test.result == 'skipped') && (needs.build-and-push-docker-image.result == 'success')
     runs-on: ubuntu-latest
-    needs: [e2e-test, build-and-push-docker-image]
+    needs: [e2e-test, build-and-push-docker-image, build-and-push-docker-image]
     permissions:
-      contents: read
+      contents: write
+      packages: write
+
     defaults:
       run:
         shell: bash
@@ -298,28 +378,69 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
+          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
           persist-credentials: false
 
       - name: Install yq
         run: sudo snap install yq --channel=v4/stable
 
       - name: "[PROD] Set images and commit"
-        if: github.ref == 'refs/heads/main'
+        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'main') || (github.ref == 'refs/heads/main')
         run: |
           git config --global user.email github@ci.push && \
           git config --global user.name "Github action" && \
-          git remote set-url origin https://${{ secrets.GH_COMMIT_PAT }}@github.com/${{ github.repository }}.git && \
+          git remote add pat-origin https://${{ secrets.GH_COMMIT_PAT }}@github.com/${{ github.repository }}.git && \
           /snap/bin/yq -i '.admin.deploymentContainer.image = "ghcr.io/${{ github.repository_owner }}/admin-server:${{ needs.build-and-push-docker-image.outputs.image_tag }}"' ./operations/deployments/openstad-headless/environments/prod/images.yml && \
+          /snap/bin/yq -i '.admin.deploymentContainer.image = "ghcr.io/${{ github.repository_owner }}/admin-server:${{ needs.build-and-push-docker-image.outputs.image_tag }}"' ./charts/openstad-headless/values.yaml && \
           /snap/bin/yq -i '.api.deploymentContainer.image = "ghcr.io/${{ github.repository_owner }}/api-server:${{ needs.build-and-push-docker-image.outputs.image_tag }}"' ./operations/deployments/openstad-headless/environments/prod/images.yml && \
+          /snap/bin/yq -i '.api.deploymentContainer.image = "ghcr.io/${{ github.repository_owner }}/api-server:${{ needs.build-and-push-docker-image.outputs.image_tag }}"' ./charts/openstad-headless/values.yaml && \
           /snap/bin/yq -i '.cms.deploymentContainer.image = "ghcr.io/${{ github.repository_owner }}/cms-server:${{ needs.build-and-push-docker-image.outputs.image_tag }}"' ./operations/deployments/openstad-headless/environments/prod/images.yml && \
+          /snap/bin/yq -i '.cms.deploymentContainer.image = "ghcr.io/${{ github.repository_owner }}/cms-server:${{ needs.build-and-push-docker-image.outputs.image_tag }}"' ./charts/openstad-headless/values.yaml && \
           /snap/bin/yq -i '.auth.deploymentContainer.image = "ghcr.io/${{ github.repository_owner }}/auth-server:${{ needs.build-and-push-docker-image.outputs.image_tag }}"' ./operations/deployments/openstad-headless/environments/prod/images.yml && \
+          /snap/bin/yq -i '.auth.deploymentContainer.image = "ghcr.io/${{ github.repository_owner }}/auth-server:${{ needs.build-and-push-docker-image.outputs.image_tag }}"' ./charts/openstad-headless/values.yaml && \
           /snap/bin/yq -i '.image.deploymentContainer.image = "ghcr.io/${{ github.repository_owner }}/image-server:${{ needs.build-and-push-docker-image.outputs.image_tag }}"' ./operations/deployments/openstad-headless/environments/prod/images.yml && \
+          /snap/bin/yq -i '.image.deploymentContainer.image = "ghcr.io/${{ github.repository_owner }}/image-server:${{ needs.build-and-push-docker-image.outputs.image_tag }}"' ./charts/openstad-headless/values.yaml && \
           git add operations/deployments/openstad-headless/environments/prod/images.yml && \
+          git add charts/openstad-headless/values.yaml && \
           git commit -m "ci: prod release ${{ needs.build-and-push-docker-image.outputs.image_tag }}" && \
-          git push origin main
+          git push pat-origin main && \
+          git fetch origin main && \
+          git checkout -B main origin/main
+
+      - name: "[PROD] Install Helm"
+        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'main') || (github.ref == 'refs/heads/main')
+        uses: azure/setup-helm@v3
+        with:
+          version: v3.5.4
+
+      - name: "[PROD] Helm Lint Charts"
+        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'main') || (github.ref == 'refs/heads/main')
+        run: |
+          for dir in $(ls -d charts/*/); do
+          # remove trailing slash from dir
+            dir=$(echo $dir | sed 's:/*$::')
+            helm lint $dir -f $dir/values.yaml --strict || exit 1
+          done
+
+      - name: "[PROD] Helm Deps"
+        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'main') || (github.ref == 'refs/heads/main')
+        run: |
+          for dir in $(ls -d charts/*/); do
+            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
+          done
+
+      - name: "[PROD] Run chart-releaser"
+        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'main') || (github.ref == 'refs/heads/main')
+        uses: helm/chart-releaser-action@v1.6.0
+        env:
+          CR_TOKEN: '${{ secrets.GH_COMMIT_PAT }}'
+          CR_GENERATE_RELEASE_NOTES: true
+          CR_RELEASE_NAME_TEMPLATE: 'v{{ .Version }}'
+        with:
+          charts_dir: charts
 
       - name: "[ACC] Set images and commit"
-        if: github.ref == 'refs/heads/develop'
+        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.branch == 'develop') || (github.ref == 'refs/heads/develop')
         run: |
           git config --global user.email github@ci.push && \
           git config --global user.name "Github action" && \
